export type ProgramTheme = {
  n: number;
  title: string;
};

export type ProgramSubject = {
  slug: string;
  code: string;
  weeklyHours: number;
  credits: number;
  period: "Anual";
  objective: string;
  themes: ProgramTheme[];
};

export const YEAR = {
  label: "Cuarto año",
  academicYear: "2025-2026",
  university: "Universidad Católica del Táchira",
  faculty: "Facultad de Ciencias Jurídicas y Políticas",
  school: "Escuela de Derecho",
  career: "Derecho",
  subjectCount: 8,
  weeklyHours: 26,
  credits: 41,
  ratified: "Consejo de Facultad, Reunión Ordinaria N° 173 · 08-10-2025",
} as const;

export const PROGRAM: Record<string, ProgramSubject> = {
  "civil-iv": {
    slug: "civil-iv",
    code: "J0014000",
    weeklyHours: 5,
    credits: 9,
    period: "Anual",
    objective:
      "Teoría general del contrato, contratos en particular y las garantías del Código Civil venezolano, para resolver problemas prácticos.",
    themes: [
      { n: 1, title: "Introducción al estudio de los contratos" },
      { n: 2, title: "La donación" },
      { n: 3, title: "Generalidades sobre la venta" },
      { n: 4, title: "Elementos esenciales de la venta — consentimiento" },
      { n: 5, title: "Elementos esenciales de la venta — capacidad, objeto y precio" },
      { n: 6, title: "Obligaciones del vendedor — transferencia y tradición" },
      { n: 7, title: "Saneamiento por evicción" },
      { n: 8, title: "Saneamiento por vicios ocultos" },
      { n: 9, title: "Obligaciones del comprador" },
      { n: 10, title: "El retracto" },
      { n: 11, title: "Ventas especiales" },
      { n: 12, title: "Cesión de créditos y permuta" },
      { n: 13, title: "Enfiteusis" },
      { n: 14, title: "Contrato de arrendamiento" },
      { n: 15, title: "Extinción del arrendamiento" },
      { n: 16, title: "Legislación inquilinaria" },
      { n: 17, title: "El reintegro" },
      { n: 18, title: "Preferencia ofertiva y retracto legal arrendaticio" },
      { n: 19, title: "Consignación inquilinaria" },
      { n: 20, title: "Prestación de servicios y contrato de obra" },
      { n: 21, title: "Obligaciones del contratista" },
      { n: 22, title: "Obligaciones del comitente" },
      { n: 23, title: "Responsabilidad decenal" },
      { n: 24, title: "La sociedad" },
      { n: 25, title: "El mandato" },
      { n: 26, title: "La transacción" },
      { n: 27, title: "El comodato" },
      { n: 28, title: "Introducción a las garantías" },
      { n: 29, title: "Fianza — inicio" },
      { n: 30, title: "Fianza — efectos y extinción" },
      { n: 31, title: "Prenda — inicio" },
      { n: 32, title: "Prenda — efectos y extinción" },
      { n: 33, title: "Hipoteca — noción y caracteres" },
      { n: 34, title: "Hipoteca — efectos" },
      { n: 35, title: "Hipoteca — transmisión y extinción" },
    ],
  },
  administrativo: {
    slug: "administrativo",
    code: "J0014001",
    weeklyHours: 3,
    credits: 5,
    period: "Anual",
    objective:
      "El procedimiento contencioso-administrativo venezolano, su jurisdicción y la LOJCA.",
    themes: [
      { n: 1, title: "Sistema contencioso-administrativo y justicia administrativa" },
      { n: 2, title: "Estructura orgánica del contencioso en Venezuela" },
      { n: 3, title: "Competencia de los órganos de la jurisdicción" },
      { n: 4, title: "Vías o medios de proceder" },
      { n: 5, title: "Requisitos de inadmisibilidad" },
      { n: 6, title: "Caracteres del proceso contencioso-administrativo" },
      { n: 7, title: "Sujetos del proceso administrativo" },
      { n: 8, title: "Juicios de nulidad contra actos de efectos generales" },
      { n: 9, title: "Juicios de nulidad contra actos de efectos particulares" },
      { n: 10, title: "Doctrina jurisprudencial del proceso" },
      { n: 11, title: "Demandas contra la República" },
      { n: 12, title: "La sentencia en el contencioso-administrativo" },
      { n: 13, title: "Efectos del recurso" },
      { n: 14, title: "Contenciosos especiales" },
      { n: 15, title: "Responsabilidad de la Administración" },
      { n: 16, title: "Reforma del contencioso administrativo" },
    ],
  },
  procesal: {
    slug: "procesal",
    code: "J0014002",
    weeklyHours: 3,
    credits: 6,
    period: "Anual",
    objective:
      "El procedimiento ordinario: introducción, instrucción, decisión, ejecución y medidas cautelares.",
    themes: [
      { n: 1, title: "Definiciones y tiempos del procedimiento ordinario" },
      { n: 2, title: "Introducción de la causa — la demanda" },
      { n: 3, title: "El emplazamiento y la citación" },
      { n: 4, title: "Cuestiones previas" },
      { n: 5, title: "Contestación a la demanda" },
      { n: 6, title: "Reconvención" },
      { n: 7, title: "Intervención de terceros" },
      { n: 8, title: "Lapso probatorio" },
      { n: 9, title: "Vista y sentencia en primera instancia" },
      { n: 10, title: "La sentencia" },
      { n: 11, title: "La apelación" },
      { n: 12, title: "Procedimiento en segunda instancia" },
      { n: 13, title: "Ejecución de la sentencia" },
      { n: 14, title: "Embargo ejecutivo, depósito, justiprecio y remate" },
      { n: 15, title: "Medidas preventivas" },
      { n: 16, title: "Embargo preventivo, secuestro y prohibición de enajenar y gravar" },
      { n: 17, title: "Procedimiento de las medidas preventivas" },
      { n: 18, title: "Procedimiento incidental supletorio" },
    ],
  },
  mercantil: {
    slug: "mercantil",
    code: "J0014003",
    weeklyHours: 4,
    credits: 7,
    period: "Anual",
    objective:
      "Aspectos generales del Derecho Mercantil, el empresario, las sociedades mercantiles y los contratos mercantiles.",
    themes: [
      { n: 1, title: "Aspectos generales del Derecho Mercantil" },
      { n: 2, title: "Fuentes del Derecho Mercantil" },
      { n: 3, title: "La actividad comercial y el acto de comercio" },
      { n: 4, title: "Auxiliares del empresario" },
      { n: 5, title: "Identificación del empresario y firma comercial" },
      { n: 6, title: "Derechos intelectuales y propiedad industrial" },
      { n: 7, title: "Registro de comercio" },
      { n: 8, title: "Contabilidad mercantil" },
      { n: 9, title: "Derecho de la competencia" },
      { n: 10, title: "Derecho Mercantil Internacional" },
      { n: 11, title: "Aspectos generales de las sociedades" },
      { n: 12, title: "Personalidad jurídica de las sociedades mercantiles" },
      { n: 13, title: "Sociedades irregulares" },
      { n: 14, title: "Sociedad anónima — aspectos generales" },
      { n: 15, title: "Sociedad anónima — capital social" },
      { n: 16, title: "Estructura legal de la sociedad anónima" },
      { n: 17, title: "Sociedad anónima de oferta pública" },
      { n: 18, title: "Sociedad de responsabilidad limitada" },
      { n: 19, title: "Sociedades de personas" },
      { n: 20, title: "Extinción de las sociedades mercantiles" },
      { n: 21, title: "Obligaciones mercantiles" },
      { n: 22, title: "Contratos mercantiles nominados" },
      { n: 23, title: "Contratos atípicos e innominados" },
      { n: 24, title: "Contratación internacional" },
      { n: 25, title: "Garantías mercantiles" },
    ],
  },
  laboral: {
    slug: "laboral",
    code: "J0014004",
    weeklyHours: 4,
    credits: 7,
    period: "Anual",
    objective:
      "Sujetos de la relación laboral, el contrato de trabajo, su dinámica y las condiciones de trabajo.",
    themes: [
      { n: 1, title: "Evolución histórica del trabajo humano" },
      { n: 2, title: "Evolución del trabajo en Venezuela" },
      { n: 3, title: "Derecho internacional del trabajo" },
      { n: 4, title: "Concepto y naturaleza del Derecho del Trabajo" },
      { n: 5, title: "Carácter de orden público" },
      { n: 6, title: "Base constitucional" },
      { n: 7, title: "Libertad de trabajo" },
      { n: 8, title: "Fuentes del Derecho del Trabajo" },
      { n: 9, title: "La prescripción en materia laboral" },
      { n: 10, title: "Las personas en el Derecho del Trabajo" },
      { n: 11, title: "El patrono" },
      { n: 12, title: "La relación y el contrato de trabajo" },
      { n: 13, title: "Efectos del contrato" },
      { n: 14, title: "Clases de contrato según su duración" },
      { n: 15, title: "Sustitución de patronos" },
      { n: 16, title: "Suspensión de la relación de trabajo" },
      { n: 17, title: "Terminación de la relación de trabajo" },
      { n: 18, title: "Reglas comunes al despido y al retiro" },
      { n: 19, title: "El despido" },
      { n: 20, title: "El retiro" },
      { n: 21, title: "Estabilidad en el trabajo" },
      { n: 22, title: "Prestación de antigüedad" },
      { n: 23, title: "La remuneración" },
      { n: 24, title: "Clases de salario" },
      { n: 25, title: "El pago del salario" },
      { n: 26, title: "Protección del salario" },
      { n: 27, title: "Intervención del Estado en la fijación de salarios" },
      { n: 28, title: "Participación en los beneficios" },
      { n: 29, title: "Condiciones de trabajo" },
      { n: 30, title: "La jornada de trabajo" },
      { n: 31, title: "La jornada extraordinaria" },
      { n: 32, title: "Descanso semanal y días feriados" },
      { n: 33, title: "Las vacaciones" },
      { n: 34, title: "Protección a la maternidad y la familia" },
    ],
  },
  pruebas: {
    slug: "pruebas",
    code: "J0014005",
    weeklyHours: 3,
    credits: 5,
    period: "Anual",
    objective:
      "Principios del derecho probatorio y manejo de los medios de prueba en la etapa de instrucción.",
    themes: [
      { n: 1, title: "El derecho probatorio y su importancia" },
      { n: 2, title: "Principios generales del derecho probatorio" },
      { n: 3, title: "Los sistemas probatorios" },
      { n: 4, title: "El objeto de la prueba" },
      { n: 5, title: "La carga de la prueba" },
      { n: 6, title: "Clasificación de la prueba" },
      { n: 7, title: "El procedimiento probatorio" },
      { n: 8, title: "La confesión" },
      { n: 9, title: "Las posiciones juradas" },
      { n: 10, title: "El juramento" },
      { n: 11, title: "La prueba de testigos" },
      { n: 12, title: "Procedimiento de la prueba testimonial" },
      { n: 13, title: "Inhabilidad del testigo" },
      { n: 14, title: "La experticia" },
      { n: 15, title: "La inspección judicial" },
      { n: 16, title: "La prueba por escrito" },
      { n: 17, title: "Copias, exhibición e informes" },
      { n: 18, title: "Tacha de instrumentos" },
      { n: 19, title: "Reconocimiento de instrumentos privados" },
      { n: 20, title: "Indicios y presunciones" },
      { n: 21, title: "Medios de prueba no prohibidos" },
      { n: 22, title: "Valoración y apreciación de la prueba" },
      { n: 23, title: "Innovaciones tecnológicas y la prueba" },
      { n: 24, title: "La oralidad y la prueba" },
    ],
  },
  "practicas-adm": {
    slug: "practicas-adm",
    code: "J0014006",
    weeklyHours: 2,
    credits: 1,
    period: "Anual",
    objective:
      "Destrezas prácticas de Derecho Administrativo: expedientes, recursos, contencioso y amparo.",
    themes: [
      { n: 1, title: "Ámbito de aplicación de la LOPA" },
      { n: 2, title: "Iniciación del procedimiento administrativo" },
      { n: 3, title: "Sustanciación del expediente" },
      { n: 4, title: "Terminación del expediente" },
      { n: 5, title: "Notificación administrativa" },
      { n: 6, title: "Recursos administrativos" },
      { n: 7, title: "Procedimientos especiales" },
      { n: 8, title: "Contencioso administrativo (escrito de demanda)" },
      { n: 9, title: "Amparo constitucional" },
    ],
  },
  "practicas-proc": {
    slug: "practicas-proc",
    code: "J0014007",
    weeklyHours: 2,
    credits: 1,
    period: "Anual",
    objective:
      "Casos prácticos civiles y mercantiles: demanda, contestación, pruebas, informes e impugnación.",
    themes: [
      { n: 1, title: "Partes, legitimación, pretensión y poder" },
      { n: 2, title: "Demanda, providenciación y citación" },
      { n: 3, title: "Cuestiones previas y saneamiento" },
      { n: 4, title: "Contestación y reconvención" },
      { n: 5, title: "Promoción, oposición, admisión y evacuación de pruebas" },
      { n: 6, title: "Informes y observaciones" },
      { n: 7, title: "Análisis de sentencias" },
      { n: 8, title: "Reclamo, apelación y adhesión" },
    ],
  },
};

export const TUTOR_STARTERS: Record<string, string[]> = {
  "civil-iv": [
    "Explícame el contrato de venta como para un oral: elementos, obligaciones del vendedor y saneamiento.",
    "Diferencias entre fianza, prenda e hipoteca en el Código Civil venezolano.",
    "Armame 8 preguntas de parcial sobre arrendamiento e inquilinato.",
  ],
  administrativo: [
    "¿Qué distingue el contencioso de nulidad de las demandas contra la República?",
    "Explícame los requisitos de inadmisibilidad en la LOJCA, con lapsos.",
    "Hazme un esquema de la sentencia contencioso-administrativa y sus efectos.",
  ],
  procesal: [
    "Paso a paso: de la demanda a la traba de la litis, con lapsos del CPC.",
    "Cuestiones previas: cuáles son, cuándo se oponen y qué pasa si prosperan.",
    "Redactá un esquema de contestación de demanda con reconvención.",
  ],
  mercantil: [
    "¿Qué es el acto de comercio y cómo se distingue del acto civil?",
    "Sociedad anónima: capital, asambleas, administradores y comisario.",
    "Cinco diferencias entre compraventa civil y compraventa mercantil.",
  ],
  laboral: [
    "Elementos del contrato de trabajo y presunciones de la LOTTT.",
    "Despido justificado vs. retiro justificado, con consecuencias.",
    "Cómo se calcula la prestación de antigüedad. Explicámelo con un ejemplo.",
  ],
  pruebas: [
    "Principios del derecho probatorio y el sistema de sana crítica en Venezuela.",
    "Carga de la prueba: hechos constitutivos, impeditivos y extintivos.",
    "Documento público vs. documento privado: fuerza probatoria y tacha.",
  ],
  "practicas-adm": [
    "Redactá un modelo de recurso de reconsideración contra un acto municipal.",
    "Estructura de un escrito de nulidad contencioso-administrativa.",
    "¿Cuándo va amparo autónomo y cuándo nulidad con amparo cautelar?",
  ],
  "practicas-proc": [
    "Modelo breve de contestación de demanda por incumplimiento de contrato de venta.",
    "Cómo se promueven pruebas en el lapso del procedimiento ordinario.",
    "Checklist para revisar una sentencia de primera instancia antes de apelar.",
  ],
};

export function getProgram(slug: string): ProgramSubject | undefined {
  return PROGRAM[slug];
}

export function syllabusForPrompt(slug: string): string {
  const p = PROGRAM[slug];
  if (!p) return "";
  const themes = p.themes.map((t) => `${t.n}. ${t.title}`).join("\n");
  return [
    `${p.code} · ${p.period} · ${p.weeklyHours} h/sem · ${p.credits} UC`,
    `Objetivo: ${p.objective}`,
    "Temario oficial:",
    themes,
  ].join("\n");
}
