/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CuadernoRouteImport } from './routes/cuaderno'
import { Route as EnfoqueRouteImport } from './routes/enfoque'
import { Route as ExamenesRouteImport } from './routes/examenes'
import { Route as HorarioRouteImport } from './routes/horario'
import { Route as MateriasRouteImport } from './routes/materias'
import { Route as PracticaRouteImport } from './routes/practica'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as MateriasSlugRouteImport } from './routes/materias_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadernoRoute = CuadernoRouteImport.update({
  id: '/cuaderno',
  path: '/cuaderno',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfoqueRoute = EnfoqueRouteImport.update({
  id: '/enfoque',
  path: '/enfoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenesRoute = ExamenesRouteImport.update({
  id: '/examenes',
  path: '/examenes',
  getParentRoute: () => rootRouteImport,
} as any)
const HorarioRoute = HorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasRoute = MateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaRoute = PracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriasSlugRoute = MateriasSlugRouteImport.update({
  id: '/materias_/$slug',
  path: '/materias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cuaderno': typeof CuadernoRoute
  '/enfoque': typeof EnfoqueRoute
  '/examenes': typeof ExamenesRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRoute
  '/practica': typeof PracticaRoute
  '/tutor': typeof TutorRoute
  '/materias/$slug': typeof MateriasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cuaderno': typeof CuadernoRoute
  '/enfoque': typeof EnfoqueRoute
  '/examenes': typeof ExamenesRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRoute
  '/practica': typeof PracticaRoute
  '/tutor': typeof TutorRoute
  '/materias/$slug': typeof MateriasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cuaderno': typeof CuadernoRoute
  '/enfoque': typeof EnfoqueRoute
  '/examenes': typeof ExamenesRoute
  '/horario': typeof HorarioRoute
  '/materias': typeof MateriasRoute
  '/practica': typeof PracticaRoute
  '/tutor': typeof TutorRoute
  '/materias_/$slug': typeof MateriasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/cuaderno'
    | '/enfoque'
    | '/examenes'
    | '/horario'
    | '/materias'
    | '/practica'
    | '/tutor'
    | '/materias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/cuaderno'
    | '/enfoque'
    | '/examenes'
    | '/horario'
    | '/materias'
    | '/practica'
    | '/tutor'
    | '/materias/$slug'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/cuaderno'
    | '/enfoque'
    | '/examenes'
    | '/horario'
    | '/materias'
    | '/practica'
    | '/tutor'
    | '/materias_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CuadernoRoute: typeof CuadernoRoute
  EnfoqueRoute: typeof EnfoqueRoute
  ExamenesRoute: typeof ExamenesRoute
  HorarioRoute: typeof HorarioRoute
  MateriasRoute: typeof MateriasRoute
  PracticaRoute: typeof PracticaRoute
  TutorRoute: typeof TutorRoute
  MateriasSlugRoute: typeof MateriasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuaderno': {
      id: '/cuaderno'
      path: '/cuaderno'
      fullPath: '/cuaderno'
      preLoaderRoute: typeof CuadernoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfoque': {
      id: '/enfoque'
      path: '/enfoque'
      fullPath: '/enfoque'
      preLoaderRoute: typeof EnfoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examenes': {
      id: '/examenes'
      path: '/examenes'
      fullPath: '/examenes'
      preLoaderRoute: typeof ExamenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horario': {
      id: '/horario'
      path: '/horario'
      fullPath: '/horario'
      preLoaderRoute: typeof HorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias': {
      id: '/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof MateriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica': {
      id: '/practica'
      path: '/practica'
      fullPath: '/practica'
      preLoaderRoute: typeof PracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materias_/$slug': {
      id: '/materias_/$slug'
      path: '/materias/$slug'
      fullPath: '/materias/$slug'
      preLoaderRoute: typeof MateriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CuadernoRoute: CuadernoRoute,
  EnfoqueRoute: EnfoqueRoute,
  ExamenesRoute: ExamenesRoute,
  HorarioRoute: HorarioRoute,
  MateriasRoute: MateriasRoute,
  PracticaRoute: PracticaRoute,
  TutorRoute: TutorRoute,
  MateriasSlugRoute: MateriasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
